--Load CDM 5.3.1 tables
--load running psql from folder with the CSVs e.g.:
--psql -h postgis -U ohdsi -W -d synpuf_1k


--CDM tables
\COPY CARE_SITE FROM 'care_site.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY CDM_SOURCE FROM 'cdm_source.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY CONDITION_ERA FROM 'condition_era.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY CONDITION_OCCURRENCE FROM 'condition_occurrence.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY COST FROM 'cost.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY DEATH FROM 'death.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY DEVICE_EXPOSURE FROM 'device_exposure.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY DRUG_ERA FROM 'drug_era.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY DRUG_EXPOSURE FROM 'drug_exposure.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY LOCATION FROM 'location.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY MEASUREMENT FROM 'measurement.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY OBSERVATION FROM 'observation.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY OBSERVATION_PERIOD FROM 'observation_period.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY PAYER_PLAN_PERIOD FROM 'payer_plan_period.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY PERSON FROM 'person.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY PROCEDURE_OCCURRENCE FROM 'procedure_occurrence.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY PROVIDER FROM 'provider.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';
\COPY VISIT_OCCURRENCE FROM 'visit_occurrence.csv'  DELIMITER E'\t' CSV ENCODING 'UTF8';

--VOCABULARY TABLES
--alter table vocabulary alter column vocabulary_version drop not null; CAN be required

\COPY CONCEPT_ANCESTOR FROM 'CONCEPT_ANCESTOR.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b';
\COPY CONCEPT_CLASS FROM 'CONCEPT_CLASS.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b';
\COPY CONCEPT FROM 'CONCEPT.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b';
\COPY CONCEPT_RELATIONSHIP FROM 'CONCEPT_RELATIONSHIP.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b';
\COPY CONCEPT_SYNONYM FROM 'CONCEPT_SYNONYM.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b';
\COPY DOMAIN FROM 'DOMAIN.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b';
\COPY DRUG_STRENGTH FROM 'DRUG_STRENGTH.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b';
\COPY RELATIONSHIP FROM 'RELATIONSHIP.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b';
\COPY VOCABULARY FROM 'VOCABULARY.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b';